swagger: "2.0"
info:
  version: "0.0.1"
  title: API
# during dev, should point to your local machine
host: localhost:3002
# basePath prefixes all resource paths
basePath: /
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /swagger:
    x-swagger-pipe: swagger_raw

  /ping:
    x-swagger-router-controller: ping
    get:
      description: pong
      operationId: pong
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/PingResponse"


# complex objects have schema definitions
definitions:
  PingResponse:
    required:
      - message
      - time
    properties:
      message:
        type: string
      time:
        type: number

  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
