default:
  port: 3001
  cache_assets: true
  postgresHost: 127.0.0.1
  postgresPort: 5432
  postgresUser: postgres
  postgresPassword: password
  postgresDatabase: postgres
  postgresPoolMin: 0
  postgresPoolMin: 10

development:
  cache_assets: false

production: &production
  port: #{process.env.PORT}
  secret_key: 7EHDWHD9W9U3WSFB949394BWYFG8WE78F1

# aliases must be defined before you include!
staging:
    <<: *production
