docke## Shared payments api compose file that will be used by the generator
### Payments API
payments:
  build: payments/
  restart: always
  ports:
    - 3000:3000
  expose:
    - 3000
  links:
    - redis

redis:
  image: redis:3.2.9-alpine
  restart: always
  ports:
    - 6379:6379
  expose:
    - 6379
